.nh
.TH "LAGO" "1" "Aug 2026" "Lago CLI" "Lago CLI Manual"

.SH NAME
lago-features-create - Create a feature


.SH SYNOPSIS
\fBlago features create [flags]\fP


.SH DESCRIPTION
This endpoint creates a new feature representing an entitlement component of your application.


.SH OPTIONS
\fB--code\fP=""
	Unique code used to identify the feature.

.PP
\fB--description\fP=""
	Internal description of the feature.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--idempotency-key\fP=""
	Idempotency key for safe mutation retries

.PP
\fB--input\fP=""
	Complete JSON request body or @file.json

.PP
\fB--name\fP=""
	Name of the feature.

.PP
\fB--privileges\fP=""
	Privileges associated with this feature. Can be empty.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	Override the Lago API key

.PP
\fB--api-url\fP=""
	Override the Lago API URL

.PP
\fB--confirm\fP=""
	Confirm a dangerous operation with its resource identifier

.PP
\fB--dry-run\fP[=false]
	Print mutating requests without sending them

.PP
\fB--insecure\fP[=false]
	Allow insecure HTTP or TLS for self-hosted Lago

.PP
\fB--mode\fP=""
	Environment mode: live or test

.PP
\fB--no-retry\fP[=false]
	Disable automatic retries

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, or yaml

.PP
\fB--profile\fP=""
	Named profile to use

.PP
\fB--query\fP=""
	JMESPath expression applied to the response

.PP
\fB--timeout\fP=30s
	Total request timeout

.PP
\fB--timing\fP[=false]
	Print request latency breakdown

.PP
\fB--verbose\fP[=false]
	Print redacted request and response details


.SH EXAMPLE
.EX
  lago features create --input @payload.json
.EE


.SH SEE ALSO
\fBlago-features(1)\fP
