.nh
.TH "LAGO" "1" "Aug 2026" "Lago CLI" "Lago CLI Manual"

.SH NAME
lago-customers-portal-url - Get a customer portal URL


.SH SYNOPSIS
\fBlago customers portal-url  [flags]\fP


.SH DESCRIPTION
Retrieves an embeddable link for displaying a customer portal.

.PP
This endpoint allows you to fetch the URL that can be embedded to provide customers access to a dedicated portal


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for portal-url

.PP
\fB--watch\fP[=false]
	Poll and re-render when the response changes

.PP
\fB--watch-interval\fP=2s
	Polling interval used with --watch


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	Override the Lago API key

.PP
\fB--api-url\fP=""
	Override the Lago API URL

.PP
\fB--confirm\fP=""
	Confirm a dangerous operation with its resource identifier

.PP
\fB--dry-run\fP[=false]
	Print mutating requests without sending them

.PP
\fB--insecure\fP[=false]
	Allow insecure HTTP or TLS for self-hosted Lago

.PP
\fB--mode\fP=""
	Environment mode: live or test

.PP
\fB--no-retry\fP[=false]
	Disable automatic retries

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, or yaml

.PP
\fB--profile\fP=""
	Named profile to use

.PP
\fB--query\fP=""
	JMESPath expression applied to the response

.PP
\fB--timeout\fP=30s
	Total request timeout

.PP
\fB--timing\fP[=false]
	Print request latency breakdown

.PP
\fB--verbose\fP[=false]
	Print redacted request and response details


.SH EXAMPLE
.EX
  lago customers portal-url <external_customer_id>
.EE


.SH SEE ALSO
\fBlago-customers(1)\fP
