.nh
.TH "LAGO" "1" "Aug 2026" "Lago CLI" "Lago CLI Manual"

.SH NAME
lago-plans-update - Update a plan


.SH SYNOPSIS
\fBlago plans update  [flags]\fP


.SH DESCRIPTION
This endpoint updates a specific plan with subscription and usage-based charges. It supports flexible billing cadence (in-advance or in-arrears) and allows for both recurring and metered charges.


.SH OPTIONS
\fB--amount-cents\fP=""
	The base cost of the plan, excluding any applicable taxes, that is billed on a recurring basis. This value is defined at 0 if your plan is a pay-as-you-go plan.

.PP
\fB--amount-currency\fP=""
	The currency of the plan. It indicates the monetary unit in which the plan's cost, including taxes and usage-based charges, is expressed.; one of: AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BIF, BMD, BND, BOB, BRL, BSD, BWP, BYN, BZD, CAD, CDF, CHF, CLF, CLP, CNY, COP, CRC, CVE, CZK, DJF, DKK, DOP, DZD, EGP, ETB, EUR, FJD, FKP, GBP, GEL, GHS, GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HRK, HTG, HUF, IDR, ILS, INR, ISK, JMD, JPY, KES, KGS, KHR, KMF, KRW, KYD, KZT, LAK, LBP, LKR, LRD, LSL, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRO, MUR, MVR, MWK, MXN, MYR, MZN, NAD, NGN, NIO, NOK, NPR, NZD, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR, SBD, SCR, SEK, SGD, SHP, SLL, SOS, SRD, STD, SZL, THB, TJS, TOP, TRY, TTD, TWD, TZS, UAH, UGX, USD, UYU, UZS, VND, VUV, WST, XAF, XCD, XOF, XPF, YER, ZAR, ZMW

.PP
\fB--bill-charges-monthly\fP=""
	This field, when set to 'true', enables to invoice usage-based charges on monthly basis, even if the cadence of the plan is yearly or semiannual. This allows customers to pay charges overage on a monthly basis. This can be set to true only if the plan's interval is 'yearly' or 'semiannual'.

.PP
\fB--bill-fixed-charges-monthly\fP=""
	This field, when set to 'true', enables to invoice fixed charges on monthly basis, even if the cadence of the plan is 'yearly' or 'semiannual'. This allows customers to pay fixed charges on a monthly basis. This can be set to true only if the plan's interval is 'yearly' or 'semiannual'.

.PP
\fB--cascade-updates\fP=""
	This field determines whether the changes made to the plan should be cascaded to the children plans. When set to 'true', the changes will be cascaded into children. Conversely, when set to 'false', the changes will only be applied to the plan itself. If not defined in the request, default value is 'false'.

.PP
\fB--charges\fP=""
	Additional usage-based charges for this plan.

.PP
\fB--code\fP=""
	The code of the plan. It serves as a unique identifier associated with a particular plan. The code is typically used for internal or system-level identification purposes, like assigning a subscription, for instance.

.PP
\fB--description\fP=""
	The description on the plan.

.PP
\fB--fixed-charges\fP=""
	Additional fixed charges for this plan.

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for update

.PP
\fB--input\fP=""
	Complete JSON request body or @file.json

.PP
\fB--interval\fP=""
	The interval used for recurring billing. It represents the frequency at which subscription billing occurs. The interval can be one of the following values: 'yearly', 'semiannual', 'quarterly', 'monthly', or 'weekly'.; one of: weekly, monthly, quarterly, semiannual, yearly

.PP
\fB--invoice-display-name\fP=""
	Specifies the name that will be displayed on an invoice. If no value is set for this field, the name of the plan will be used as the default display name.

.PP
\fB--metadata\fP=""
	Metadata to set as key-value pairs. Keys are strings (max 100 characters), values can be strings (max 255 characters) or null.

.PP
\fB--minimum-commitment-amount-cents\fP=""
	The amount of the minimum commitment in cents.

.PP
\fB--minimum-commitment-invoice-display-name\fP=""
	Specifies the name that will be displayed on an invoice. If no value is set for this field, the default name will be used as the display name.

.PP
\fB--minimum-commitment-tax-codes\fP=""
	List of unique code used to identify the taxes.

.PP
\fB--name\fP=""
	The name of the plan.

.PP
\fB--pay-in-advance\fP=""
	This field determines the billing timing for the plan. When set to 'true', the base cost of the plan is due at the beginning of each billing period. Conversely, when set to 'false', the base cost of the plan is due at the end of each billing period.

.PP
\fB--tax-codes\fP=""
	List of unique code used to identify the taxes.

.PP
\fB--trial-period\fP=""
	The duration in days during which the base cost of the plan is offered for free.

.PP
\fB--usage-thresholds\fP=""
	List of usage thresholds to apply to the plan.


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	Override the Lago API key

.PP
\fB--api-url\fP=""
	Override the Lago API URL

.PP
\fB--confirm\fP=""
	Confirm a dangerous operation with its resource identifier

.PP
\fB--dry-run\fP[=false]
	Print mutating requests without sending them

.PP
\fB--insecure\fP[=false]
	Allow insecure HTTP or TLS for self-hosted Lago

.PP
\fB--mode\fP=""
	Environment mode: live or test

.PP
\fB--no-retry\fP[=false]
	Disable automatic retries

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, or yaml

.PP
\fB--profile\fP=""
	Named profile to use

.PP
\fB--query\fP=""
	JMESPath expression applied to the response

.PP
\fB--timeout\fP=30s
	Total request timeout

.PP
\fB--timing\fP[=false]
	Print request latency breakdown

.PP
\fB--verbose\fP[=false]
	Print redacted request and response details


.SH EXAMPLE
.EX
  lago plans update <code> --input @payload.json
.EE


.SH SEE ALSO
\fBlago-plans(1)\fP
