.nh
.TH "LAGO" "1" "Sep 2026" "Lago CLI" "Lago CLI Manual"

.SH NAME
lago-wallets-create-customer-wallet-alert - Create wallet alert(s)


.SH SYNOPSIS
\fBlago wallets create-customer-wallet-alert   [flags]\fP


.SH DESCRIPTION
This endpoint allows you to create new alerts for a wallet. Send a single alert object wrapped in \fBalert\fR key to create one alert, or an array of alert objects wrapped in \fBalerts\fR key to create multiple alerts atomically.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for create-customer-wallet-alert

.PP
\fB--idempotency-key\fP=""
	Idempotency key for safe mutation retries

.PP
\fB--input\fP=""
	Complete JSON request body or @file.json


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	Override the Lago API key

.PP
\fB--api-url\fP=""
	Override the Lago API URL

.PP
\fB--confirm\fP=""
	Confirm a dangerous operation with its resource identifier

.PP
\fB--dry-run\fP[=false]
	Print mutating requests without sending them

.PP
\fB--insecure\fP[=false]
	Allow insecure HTTP or TLS for self-hosted Lago

.PP
\fB--mode\fP=""
	Environment mode: live or test

.PP
\fB--no-retry\fP[=false]
	Disable automatic retries

.PP
\fB-o\fP, \fB--output\fP="table"
	Output format: table, json, or yaml

.PP
\fB--profile\fP=""
	Named profile to use

.PP
\fB--query\fP=""
	JMESPath expression applied to the response

.PP
\fB--timeout\fP=30s
	Total request timeout

.PP
\fB--timing\fP[=false]
	Print request latency breakdown

.PP
\fB--verbose\fP[=false]
	Print redacted request and response details


.SH EXAMPLE
.EX
  lago wallets create-customer-wallet-alert <external_customer_id> <wallet_code> --input @payload.json
  lago wallets create-customer-wallet-alert <external_customer_id> <wallet_code> --input @payload.json --output json  # full resource
.EE


.SH SEE ALSO
\fBlago-wallets(1)\fP
